import React, { useEffect, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Workflow, FileCode, ChevronRight, Copy, Check } from 'lucide-react'
import { portalApi, PortalArchFile } from '../../services/portalApi'
import { MermaidBlock } from '../../components/MarkdownRenderer'

const IntelligenceCallFlow: React.FC = () => {
    const { projectId, commitHash } = useOutletContext<{ projectId: string; commitHash: string }>()
    const [files, setFiles] = useState<PortalArchFile[]>([])
    const [selected, setSelected] = useState<PortalArchFile | null>(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)
    const [copied, setCopied] = useState(false)

    const handleCopy = () => {
        if (!selected) return
        const code = selected.content.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '')
        navigator.clipboard.writeText(code)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    useEffect(() => {
        if (!projectId || !commitHash) return
        setLoading(true)
        portalApi.getCallFlow(projectId, commitHash)
            .then(r => {
                setFiles(r.data.files)
                if (r.data.files.length > 0) setSelected(r.data.files[0])
            })
            .catch(e => setError(e.message))
            .finally(() => setLoading(false))
    }, [projectId, commitHash])

    return (
        <div className="intel-page">
            <div className="intel-page-header">
                <h1 className="intel-page-title">
                    <span className="intel-page-title-icon" style={{ background: '#faf5ff', color: '#8b5cf6' }}>
                        <Workflow size={18} />
                    </span>
                    Call Flow
                </h1>
                <p className="intel-page-subtitle">Execution paths and request tracing through your system</p>
            </div>

            {loading ? (
                <div className="intel-loading-skeleton" style={{ height: 500, borderRadius: 14 }} />
            ) : error || files.length === 0 ? (
                <div className="intel-section-card">
                    <div className="intel-empty">
                        <Workflow size={36} className="text-slate-300" />
                        <p>{error ?? 'No execution flow diagrams available for this commit.'}</p>
                        <p className="intel-empty-hint">Call flow diagrams are generated by the EPIC-2 pipeline from your codebase structure.</p>
                    </div>
                </div>
            ) : (
                <div className="intel-arch-layout">
                    {/* Flow selector */}
                    <div className="intel-arch-sidebar">
                        <div className="intel-arch-sidebar-header">
                            <FileCode size={14} />
                            <span>{files.length} Flow{files.length !== 1 ? 's' : ''}</span>
                        </div>
                        {files.map((f, i) => (
                            <button
                                key={i}
                                onClick={() => setSelected(f)}
                                className={`intel-arch-file-btn ${selected?.path === f.path ? 'intel-arch-file-btn--active' : ''}`}
                            >
                                <span className="intel-arch-file-name">{f.name}</span>
                                <ChevronRight size={12} className="intel-arch-file-arrow" />
                            </button>
                        ))}
                    </div>

                    {/* Diagram */}
                    <div className="intel-arch-canvas">
                        {selected && (
                            <motion.div
                                key={selected.path}
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="intel-section-card intel-arch-diagram-card"
                            >
                                <div className="intel-section-card-header">
                                    <div>
                                        <h3 className="intel-section-card-title">{selected.name}</h3>
                                        <p className="intel-section-card-sub">{selected.path}</p>
                                    </div>
                                    <button onClick={handleCopy} className="intel-docs-download-btn">
                                        {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
                                        {copied ? 'Copied!' : 'Copy Code'}
                                    </button>
                                </div>
                                <div className="intel-section-card-body intel-arch-diagram-body">
                                    <MermaidBlock code={selected.content.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '')} />
                                </div>
                            </motion.div>
                        )}
                    </div>
                </div>
            )}
        </div>
    )
}

export default IntelligenceCallFlow
