import React, { useEffect, useState } from 'react'
import { useOutletContext, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Shield, FileText, TrendingUp, AlertTriangle, Layers, GitFork, Globe, ChevronRight, Sparkles } from 'lucide-react'
import { portalApi, PortalOverview } from '../../services/portalApi'
import './IntelligencePages.css'

const RISK_CONFIG: Record<string, { label: string; color: string; bg: string; border: string }> = {
    critical: { label: 'Critical', color: '#dc2626', bg: '#fef2f2', border: '#fecaca' },
    high: { label: 'High', color: '#ea580c', bg: '#fff7ed', border: '#fed7aa' },
    medium: { label: 'Medium', color: '#ca8a04', bg: '#fefce8', border: '#fef08a' },
    low: { label: 'Low', color: '#16a34a', bg: '#f0fdf4', border: '#bbf7d0' },
    unknown: { label: 'Unknown', color: '#64748b', bg: '#f8fafc', border: '#e2e8f0' },
}

function MetricCard({
    title, value, sub, icon, color, bg, border, onClick
}: {
    title: string; value: string | number; sub?: string;
    icon: React.ReactNode; color: string; bg: string; border: string
    onClick?: () => void
}) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            whileHover={onClick ? { y: -2, boxShadow: '0 8px 24px rgba(0,0,0,0.08)' } : {}}
            onClick={onClick}
            style={{ background: bg, border: `1px solid ${border}`, cursor: onClick ? 'pointer' : 'default' }}
            className="intel-metric-card"
        >
            <div className="intel-metric-icon" style={{ color, background: `${color}15` }}>{icon}</div>
            <div className="intel-metric-body">
                <div className="intel-metric-title">{title}</div>
                <div className="intel-metric-value" style={{ color }}>{value}</div>
                {sub && <div className="intel-metric-sub">{sub}</div>}
            </div>
        </motion.div>
    )
}

const IntelligenceOverview: React.FC = () => {
    const { projectId, commitHash, viewState } = useOutletContext<{ projectId: string; commitHash: string; viewState: string }>()
    const navigate = useNavigate()
    const { id: routeId } = useParams<{ id?: string }>()
    const [searchParams] = useSearchParams()

    const [data, setData] = useState<PortalOverview | null>(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)

    useEffect(() => {
        if (!projectId || !commitHash || viewState === 'no_view') {
            setLoading(false)
            return
        }
        setLoading(true)
        portalApi.getOverview(projectId, commitHash)
            .then(r => setData(r.data))
            .catch(e => setError(e.message ?? 'Failed to load overview'))
            .finally(() => setLoading(false))
    }, [projectId, commitHash, viewState])

    const goTo = (section: string) => {
        const base = routeId ? `/projects/${routeId}/intelligence` : '/intelligence'
        navigate(`${base}/${section}${searchParams.toString() ? `?${searchParams.toString()}` : ''}`)
    }

    const riskCfg = RISK_CONFIG[data?.metrics.riskLevel ?? 'unknown'] ?? RISK_CONFIG.unknown

    if (loading) return (
        <div className="intel-page">
            <div className="intel-overview-skeleton-grid">
                {[1, 2, 3, 4].map(i => (
                    <div key={i} className="intel-loading-skeleton" style={{ height: 100, borderRadius: 14 }} />
                ))}
            </div>
            <div className="intel-loading-skeleton" style={{ height: 180, marginTop: 24, borderRadius: 14 }} />
        </div>
    )

    if (viewState === 'no_view') return (
        <div className="intel-page intel-empty">
            <Shield size={40} className="text-slate-300" />
            <h3>No Intelligence Data</h3>
            <p>This project doesn't have any published intelligence data yet.</p>
            <p className="intel-empty-hint">Intelligence is generated by the DocPulse pipeline.</p>
        </div>
    )

    if (error || !data) return (
        <div className="intel-page intel-empty">
            <AlertTriangle size={40} className="text-slate-300" />
            <p>{error ?? 'No overview data available for this commit.'}</p>
        </div>
    )

    const { metrics, aiSummaryMarkdown, breakingChanges } = data

    return (
        <div className="intel-page">
            {viewState === 'preview' && (
                <div className="intel-breaking-alert" style={{ background: '#fffbeb', borderColor: '#fde68a', color: '#b45309', marginBottom: 20 }}>
                    <div className="intel-breaking-alert-header" style={{ background: '#fef3c7', color: '#b45309' }}>
                        <AlertTriangle size={16} />
                        <span>Preview Mode</span>
                    </div>
                    <div className="intel-breaking-list" style={{ padding: '8px 16px', fontSize: 13 }}>
                        You are viewing unpublished or partial intelligence data. Some metrics may be inaccurate.
                    </div>
                </div>
            )}
            {/* Header */}
            <div className="intel-page-header">
                <h1 className="intel-page-title">
                    <span className="intel-page-title-icon" style={{ background: '#eff6ff', color: '#3b82f6' }}>
                        <Sparkles size={18} />
                    </span>
                    Project Health Overview
                </h1>
                <p className="intel-page-subtitle">
                    Commit <code className="intel-mono">{commitHash?.slice(0, 7)}</code> — instant health snapshot
                </p>
            </div>

            {/* KPI Cards */}
            <div className="intel-kpi-grid">
                <MetricCard
                    title="Risk Score"
                    value={metrics.riskScore != null ? `${metrics.riskScore}/100` : '—'}
                    sub={riskCfg.label}
                    icon={<Shield size={18} />}
                    color={riskCfg.color} bg={riskCfg.bg} border={riskCfg.border}
                    onClick={() => goTo('changes')}
                />
                <MetricCard
                    title="Doc Coverage"
                    value={metrics.docCoverage != null ? `${metrics.docCoverage}%` : '—'}
                    sub="of endpoints documented"
                    icon={<FileText size={18} />}
                    color="#16a34a" bg="#f0fdf4" border="#bbf7d0"
                    onClick={() => goTo('docs')}
                />
                <MetricCard
                    title="Drift Score"
                    value={metrics.driftScore != null ? `${metrics.driftScore}%` : '—'}
                    sub="documentation drift"
                    icon={<TrendingUp size={18} />}
                    color="#ca8a04" bg="#fefce8" border="#fef08a"
                />
                <MetricCard
                    title="Breaking Changes"
                    value={metrics.breakingChangesCount}
                    sub={metrics.breakingChangesCount > 0 ? 'Detected in this commit' : 'None detected'}
                    icon={<AlertTriangle size={18} />}
                    color={metrics.breakingChangesCount > 0 ? '#dc2626' : '#16a34a'}
                    bg={metrics.breakingChangesCount > 0 ? '#fef2f2' : '#f0fdf4'}
                    border={metrics.breakingChangesCount > 0 ? '#fecaca' : '#bbf7d0'}
                    onClick={() => metrics.breakingChangesCount > 0 ? goTo('changes') : undefined}
                />
            </div>

            {/* Breaking changes alert */}
            {breakingChanges.length > 0 && (
                <motion.div
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="intel-breaking-alert"
                >
                    <div className="intel-breaking-alert-header">
                        <AlertTriangle size={16} />
                        <span>{breakingChanges.length} Breaking Change{breakingChanges.length > 1 ? 's' : ''} Detected</span>
                        <button onClick={() => goTo('changes')} className="intel-breaking-alert-btn">
                            View Details <ChevronRight size={12} />
                        </button>
                    </div>
                    <div className="intel-breaking-list">
                        {breakingChanges.slice(0, 3).map((bc: any, i: number) => (
                            <div key={i} className="intel-breaking-item">
                                <span className="intel-breaking-dot" />
                                <span>{bc.description ?? bc.change ?? bc.endpoint ?? JSON.stringify(bc)}</span>
                            </div>
                        ))}
                        {breakingChanges.length > 3 && (
                            <button onClick={() => goTo('changes')} className="intel-breaking-more">
                                +{breakingChanges.length - 3} more →
                            </button>
                        )}
                    </div>
                </motion.div>
            )}

            {/* AI Summary */}
            {aiSummaryMarkdown && (
                <motion.div
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="intel-section-card"
                    style={{ marginTop: 24 }}
                >
                    <div className="intel-section-card-header">
                        <div>
                            <h3 className="intel-section-card-title">🤖 AI Summary</h3>
                            <p className="intel-section-card-sub">Generated by DocPulse AI from commit {commitHash?.slice(0, 7)}</p>
                        </div>
                    </div>
                    <div className="intel-section-card-body intel-ai-summary">
                        <div className="intel-markdown-prose">
                            {aiSummaryMarkdown.split('\n').map((line, i) => (
                                line.trim() ? <p key={i}>{line}</p> : null
                            ))}
                        </div>
                    </div>
                </motion.div>
            )}

            {/* Quick Actions */}
            <motion.div
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.15 }}
                style={{ marginTop: 24 }}
                className="intel-quick-actions"
            >
                <h3 className="intel-quick-title">Explore Intelligence</h3>
                <div className="intel-quick-grid">
                    {[
                        { id: 'architecture', label: 'Architecture', icon: <Layers size={16} />, desc: 'System structure & layer map', color: '#3b82f6' },
                        { id: 'dependencies', label: 'Dependencies', icon: <GitFork size={16} />, desc: 'Module coupling & cycle detection', color: '#10b981' },
                        { id: 'apis', label: `APIs (${metrics.apiCount})`, icon: <Globe size={16} />, desc: 'All endpoint inventory', color: '#6366f1' },
                        { id: 'changes', label: 'Changes', icon: <AlertTriangle size={16} />, desc: 'This commit\'s impact', color: '#f59e0b' },
                    ].map(item => (
                        <button key={item.id} onClick={() => goTo(item.id)} className="intel-quick-card">
                            <div className="intel-quick-icon" style={{ color: item.color, background: `${item.color}15` }}>
                                {item.icon}
                            </div>
                            <div>
                                <div className="intel-quick-label">{item.label}</div>
                                <div className="intel-quick-desc">{item.desc}</div>
                            </div>
                            <ChevronRight size={14} className="intel-quick-arrow" />
                        </button>
                    ))}
                </div>
            </motion.div>
        </div>
    )
}

export default IntelligenceOverview
