import React, { useEffect, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Layers, FileCode, ChevronRight } from 'lucide-react'
import { portalApi, PortalArchFile } from '../../services/portalApi'
import { MermaidBlock } from '../../components/MarkdownRenderer'

const IntelligenceArchitecture: React.FC = () => {
    const { projectId, commitHash } = useOutletContext<{ projectId: string; commitHash: string }>()
    const [files, setFiles] = useState<PortalArchFile[]>([])
    const [selected, setSelected] = useState<PortalArchFile | null>(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)

    useEffect(() => {
        if (!projectId || !commitHash) return
        setLoading(true)
        portalApi.getArchitecture(projectId, commitHash)
            .then(r => {
                const f = r.data.files
                setFiles(f)
                if (f.length > 0) setSelected(f[0])
            })
            .catch(e => setError(e.message))
            .finally(() => setLoading(false))
    }, [projectId, commitHash])

    const isMermaidContent = (content: string) => {
        const t = content.trimStart()
        return (
            t.startsWith('graph') || t.startsWith('flowchart') ||
            t.startsWith('sequenceDiagram') || t.startsWith('classDiagram') ||
            t.startsWith('erDiagram') || t.startsWith('stateDiagram') ||
            t.startsWith('gantt') || t.startsWith('pie') || t.startsWith('```mermaid')
        )
    }

    return (
        <div className="intel-page">
            <div className="intel-page-header">
                <h1 className="intel-page-title">
                    <span className="intel-page-title-icon" style={{ background: '#eff6ff', color: '#3b82f6' }}>
                        <Layers size={18} />
                    </span>
                    Architecture
                </h1>
                <p className="intel-page-subtitle">System structure, layers, and component relationships</p>
            </div>

            {loading ? (
                <div className="intel-section-card">
                    <div className="intel-section-card-body">
                        <div className="intel-loading-skeleton" style={{ height: 400 }} />
                    </div>
                </div>
            ) : error || files.length === 0 ? (
                <div className="intel-section-card">
                    <div className="intel-empty">
                        <Layers size={36} className="text-slate-300" />
                        <p>{error ?? 'No architecture diagrams available for this commit.'}</p>
                        <p className="intel-empty-hint">Architecture diagrams are generated by the EPIC-2 pipeline.</p>
                    </div>
                </div>
            ) : (
                <div className="intel-arch-layout">
                    {/* File list sidebar */}
                    <div className="intel-arch-sidebar">
                        <div className="intel-arch-sidebar-header">
                            <FileCode size={14} />
                            <span>{files.length} Diagram{files.length !== 1 ? 's' : ''}</span>
                        </div>
                        {files.map((f, i) => (
                            <button
                                key={i}
                                onClick={() => setSelected(f)}
                                className={`intel-arch-file-btn ${selected?.path === f.path ? 'intel-arch-file-btn--active' : ''}`}
                            >
                                <span className="intel-arch-file-name">{f.name}</span>
                                <ChevronRight size={12} className="intel-arch-file-arrow" />
                            </button>
                        ))}
                    </div>

                    {/* Diagram canvas */}
                    <div className="intel-arch-canvas">
                        {selected && (
                            <motion.div
                                key={selected.path}
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="intel-section-card intel-arch-diagram-card"
                            >
                                <div className="intel-section-card-header">
                                    <div>
                                        <h3 className="intel-section-card-title">{selected.name}</h3>
                                        <p className="intel-section-card-sub">{selected.path}</p>
                                    </div>
                                </div>
                                <div className="intel-section-card-body intel-arch-diagram-body">
                                    {isMermaidContent(selected.content) ? (
                                        <MermaidBlock code={selected.content.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '')} />
                                    ) : (
                                        <pre className="intel-arch-raw">{selected.content}</pre>
                                    )}
                                </div>
                            </motion.div>
                        )}
                    </div>
                </div>
            )}
        </div>
    )
}

export default IntelligenceArchitecture
