import { useEffect, useState, useMemo, useCallback } from 'react'
import { useParams, useNavigate, useSearchParams } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import {
  fetchProjectById, updateProject, deleteProject, updateProjectSettings,
  inviteMember, cancelInvitation, removeMember, updateMemberRole,
  clearCurrentProject, clearError,
} from '../store/slices/projectsSlice'
import { projectsApi, documentsApi, DocumentVersion, IntelligenceView } from '../services/api'
import { useIntelligenceViewResolver } from './useIntelligenceViewResolver'

export type TabType = 'overview' | 'architecture' | 'apis_flows' | 'documents' | 'team' | 'members' | 'versioning' | 'settings'

export const useProjectDetails = () => {
  const { id } = useParams<{ id: string }>()
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const { currentProject, isLoading, error } = useAppSelector((s) => s.projects)
  const { user } = useAppSelector((s) => s.auth)

  const [activeTab, setActiveTab] = useState<TabType>('overview')
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState({ name: '', description: '' })
  const [inviteEmail, setInviteEmail] = useState('')
  const [inviteRole, setInviteRole] = useState<'member' | 'admin'>('member')
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [inviteError, setInviteError] = useState('')
  const [autoGenerateDocs, setAutoGenerateDocs] = useState(false)
  const [githubToken, setGithubToken] = useState('')
  const [showGithubToken, setShowGithubToken] = useState(false)
  const [settingsLoading, setSettingsLoading] = useState(false)
  const [docGenLoading, setDocGenLoading] = useState(false)
  const [docGenMessage, setDocGenMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const [docGenRunId, setDocGenRunId] = useState<string | null>(null)
  const [showProgressModal, setShowProgressModal] = useState(false)

  // Versioning state
  const [docVersions, setDocVersions] = useState<DocumentVersion[]>([])
  const [versionsLoading, setVersionsLoading] = useState(false)
  const [versionFilter, setVersionFilter] = useState('')

  // Intelligence state
  const [analysisLoading, setAnalysisLoading] = useState(false)
  const [latestCommitHash, setLatestCommitHash] = useState('')
  const [publishedIntelligenceView, setPublishedIntelligenceView] = useState<IntelligenceView | null>(null)
  
  const {
    loading: resolverLoading,
    error: resolverError,
    state: resolverState,
    activeView,
    commitHash: resolvedCommitHash,
  } = useIntelligenceViewResolver(currentProject?.id)

  const handleTabChange = useCallback((nextTab: TabType) => {
    setActiveTab(nextTab)
    const nextParams = new URLSearchParams(searchParams)
    if (nextTab === 'architecture' || nextTab === 'apis_flows') {
      nextParams.set('tab', nextTab)
    } else {
      nextParams.delete('tab')
    }
    setSearchParams(nextParams, { replace: true })
  }, [searchParams, setSearchParams])

  useEffect(() => {
    if (id) dispatch(fetchProjectById(id))
    return () => {
      dispatch(clearCurrentProject())
    }
  }, [dispatch, id])

  useEffect(() => {
    const tabParam = searchParams.get('tab')
    if ((tabParam === 'architecture' || tabParam === 'apis_flows') && activeTab !== tabParam) {
      setActiveTab(tabParam as TabType)
    }
    if (tabParam !== 'architecture' && tabParam !== 'apis_flows' && (activeTab === 'architecture' || activeTab === 'apis_flows')) {
      setActiveTab('overview')
    }
  }, [searchParams, activeTab])

  useEffect(() => {
    if (currentProject) {
      setEditForm({ name: currentProject.name, description: currentProject.description || '' })
      setAutoGenerateDocs(currentProject.settings?.autoGenerateDocs || false)
      setGithubToken('')
    }
  }, [currentProject])

  useEffect(() => {
    setAnalysisLoading(resolverLoading)
    setPublishedIntelligenceView(activeView)
    setLatestCommitHash(resolvedCommitHash)
  }, [resolverLoading, activeView, resolvedCommitHash])

  useEffect(() => {
    dispatch(clearError())
  }, [dispatch])

  // Load doc versions when versioning tab is active
  useEffect(() => {
    if (activeTab === 'versioning' && id) {
      setVersionsLoading(true)
      documentsApi.list(id)
        .then(r => {
          setDocVersions(r.data.documents)
          setVersionsLoading(false)
        })
        .catch(() => setVersionsLoading(false))
    }
  }, [activeTab, id])

  // Permission tiers
  const isOwner = currentProject?.memberRole === 'owner'
  const isAdmin = currentProject?.memberRole === 'admin'
  const isEditor = currentProject?.memberRole === 'editor'
  const canManageProject = isOwner || isAdmin               // settings, members, delete
  const canEditDocs = isOwner || isAdmin || isEditor        // edit documents, view versioning

  const filteredVersions = useMemo(() => {
    if (!versionFilter.trim()) return docVersions
    const q = versionFilter.toLowerCase()
    return docVersions.filter(d =>
      d.commit.toLowerCase().includes(q) ||
      d.metadata?.branch?.toLowerCase().includes(q) ||
      d.metadata?.tags?.some(t => t.toLowerCase().includes(q)) ||
      d.metadata?.version?.toLowerCase().includes(q)
    )
  }, [docVersions, versionFilter])

  const handleEditChange = useCallback((e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setEditForm((p) => ({ ...p, [e.target.name]: e.target.value }))
  }, [])

  const handleSaveChanges = useCallback(async () => {
    if (!id || !editForm.name.trim()) return
    const r = await dispatch(updateProject({ id, data: editForm }))
    if (updateProject.fulfilled.match(r)) setIsEditing(false)
  }, [id, editForm, dispatch])

  const handleDelete = useCallback(async () => {
    if (!id) return
    const r = await dispatch(deleteProject(id))
    if (deleteProject.fulfilled.match(r)) navigate('/projects')
  }, [id, dispatch, navigate])

  const handleInvite = useCallback(async (e: React.FormEvent) => {
    e.preventDefault()
    setInviteError('')
    if (!id || !inviteEmail.trim()) {
      setInviteError('Email required')
      return
    }
    const r = await dispatch(inviteMember({ projectId: id, email: inviteEmail, role: inviteRole }))
    if (inviteMember.fulfilled.match(r)) setInviteEmail('')
    else if (inviteMember.rejected.match(r)) setInviteError(r.payload as string)
  }, [id, inviteEmail, inviteRole, dispatch])

  const handleCancelInvitation = useCallback(async (invitationId: string) => {
    if (id) dispatch(cancelInvitation({ projectId: id, invitationId }))
  }, [id, dispatch])

  const handleRemoveMember = useCallback(async (memberId: string) => {
    if (id) dispatch(removeMember({ projectId: id, memberId }))
  }, [id, dispatch])

  const handleChangeRole = useCallback(async (memberId: string, newRole: string) => {
    if (id) dispatch(updateMemberRole({ projectId: id, memberId, role: newRole }))
  }, [id, dispatch])

  const handleToggleAutoGenerate = useCallback(async () => {
    if (!id) return
    setSettingsLoading(true)
    const v = !autoGenerateDocs
    const r = await dispatch(updateProjectSettings({ id, data: { autoGenerateDocs: v } }))
    if (updateProjectSettings.fulfilled.match(r)) setAutoGenerateDocs(v)
    setSettingsLoading(false)
  }, [id, autoGenerateDocs, dispatch])

  const handleSaveGithubToken = useCallback(async () => {
    if (!id) return
    setSettingsLoading(true)
    await dispatch(updateProjectSettings({ id, data: { githubAccessToken: githubToken || null } }))
    setSettingsLoading(false)
    setGithubToken('')
    setShowGithubToken(false)
  }, [id, githubToken, dispatch])

  const handleClearGithubToken = useCallback(async () => {
    if (!id) return
    setSettingsLoading(true)
    await dispatch(updateProjectSettings({ id, data: { githubAccessToken: null } }))
    setSettingsLoading(false)
  }, [id, dispatch])

  const handleTriggerDocGeneration = useCallback(async () => {
    if (!id) return
    setDocGenLoading(true)
    setDocGenMessage(null)
    try {
      const response = await projectsApi.triggerDocGeneration(id)
      const runId = response.data.runId
      setDocGenMessage({
        type: 'success',
        text: runId ? 'Analysis started — tracking progress…' : 'Analysis started!'
      })
      if (runId) {
        setDocGenRunId(runId)
        setShowProgressModal(true)
      }
    } catch (err: any) {
      const detail = err.response?.data?.detail || 'Failed'
      setDocGenMessage({ type: 'error', text: detail })
    } finally {
      setDocGenLoading(false)
    }
  }, [id])

  const handleRunComplete = useCallback(() => {
    if (id) dispatch(fetchProjectById(id))
  }, [id, dispatch])

  return {
    id,
    currentProject,
    isLoading,
    error,
    user,
    activeTab,
    setActiveTab,
    isEditing,
    setIsEditing,
    editForm,
    setEditForm,
    inviteEmail,
    setInviteEmail,
    inviteRole,
    setInviteRole,
    showDeleteConfirm,
    setShowDeleteConfirm,
    inviteError,
    setInviteError,
    autoGenerateDocs,
    setAutoGenerateDocs,
    githubToken,
    setGithubToken,
    showGithubToken,
    setShowGithubToken,
    settingsLoading,
    docGenLoading,
    docGenMessage,
    docGenRunId,
    showProgressModal,
    setShowProgressModal,
    docVersions,
    versionsLoading,
    versionFilter,
    setVersionFilter,
    analysisLoading,
    latestCommitHash,
    publishedIntelligenceView,
    resolverError,
    resolverState,
    isOwner,
    isAdmin,
    isEditor,
    canManageProject,
    canEditDocs,
    filteredVersions,
    handleTabChange,
    handleEditChange,
    handleSaveChanges,
    handleDelete,
    handleInvite,
    handleCancelInvitation,
    handleRemoveMember,
    handleChangeRole,
    handleToggleAutoGenerate,
    handleSaveGithubToken,
    handleClearGithubToken,
    handleTriggerDocGeneration,
    handleRunComplete,
  }
}
