import { useNavigate } from 'react-router-dom'
import { useProjectDetails } from '../hooks/useProjectDetails'
import AnalysisProgressModal from '../components/AnalysisProgressModal'
import DashboardLayout from '../components/DashboardLayout'
import DocumentList from '../components/DocumentList'
import CodeSearchPanel from '../components/CodeSearchPanel'
import DependencyGraphViewer from '../components/DependencyGraphViewer'
import CallGraphViewer from '../components/CallGraphViewer'
import ArchitectureGraphViewer from '../components/ArchitectureGraphViewer'
import IntelligenceStatusBadge from '../components/IntelligenceStatusBadge'
import { ChevronRight, Loader2, Shield, Layers, Workflow, FileText, Users2, Users, History, Edit3 } from 'lucide-react'
import { ProjectOverviewPanel } from '../components/ProjectOverviewPanel'
import { ProjectSettingsPanel } from '../components/ProjectSettingsPanel'
import { ProjectMembersPanel } from '../components/ProjectMembersPanel'
import { ProjectVersioningPanel } from '../components/ProjectVersioningPanel'

/** Role badge color mapping */
const roleBadgeClass = (role: string) => {
  switch (role) {
    case 'owner': return 'cr-severity--critical'
    case 'admin': return 'cr-severity--high'
    case 'editor': return 'cr-severity--medium'
    default: return 'cr-severity--info'
  }
}

const ProjectDetail = () => {
  const navigate = useNavigate()
  const details = useProjectDetails()

  const {
    id,
    currentProject,
    isLoading,
    error,
    user,
    activeTab,
    isEditing,
    setIsEditing,
    editForm,
    inviteEmail,
    setInviteEmail,
    inviteRole,
    setInviteRole,
    showDeleteConfirm,
    setShowDeleteConfirm,
    inviteError,
    autoGenerateDocs,
    githubToken,
    setGithubToken,
    showGithubToken,
    setShowGithubToken,
    settingsLoading,
    docGenLoading,
    docGenMessage,
    docGenRunId,
    showProgressModal,
    setShowProgressModal,
    docVersions,
    versionsLoading,
    versionFilter,
    setVersionFilter,
    analysisLoading,
    latestCommitHash,
    publishedIntelligenceView,
    resolverError,
    resolverState,
    isOwner,
    canManageProject,
    canEditDocs,
    filteredVersions,
    handleTabChange,
    handleEditChange,
    handleSaveChanges,
    handleDelete,
    handleInvite,
    handleCancelInvitation,
    handleRemoveMember,
    handleChangeRole,
    handleToggleAutoGenerate,
    handleSaveGithubToken,
    handleClearGithubToken,
    handleTriggerDocGeneration,
    handleRunComplete,
  } = details

  if (isLoading && !currentProject) {
    return (
      <DashboardLayout>
        <div className="cr-page">
          <div className="cr-loading">
            <div className="cr-spinner" />
          </div>
        </div>
      </DashboardLayout>
    )
  }

  if (!currentProject) {
    return (
      <DashboardLayout>
        <div className="cr-page" style={{ textAlign: 'center', paddingTop: 64 }}>
          <h3 style={{ fontSize: 16, color: 'var(--text-secondary)' }}>Project not found</h3>
          <button className="cr-doc-btn" style={{ marginTop: 8 }} onClick={() => navigate('/projects')}>
            Back to Projects
          </button>
        </div>
      </DashboardLayout>
    )
  }

  // Build tabs list based on permissions
  const tabs = [
    { key: 'overview', label: 'Overview', icon: <Shield size={13} /> },
    { key: 'architecture', label: 'Architecture', icon: <Layers size={13} /> },
    { key: 'apis_flows', label: 'APIs & Flows', icon: <Workflow size={13} /> },
    { key: 'documents', label: 'Documents', icon: <FileText size={13} /> },
    { key: 'team', label: 'Team', icon: <Users2 size={13} /> },
    { key: 'members', label: 'Members', icon: <Users size={13} /> },
    ...(canEditDocs ? [{ key: 'versioning', label: 'Versioning', icon: <History size={13} /> }] : []),
    ...(canManageProject ? [{ key: 'settings', label: 'Settings', icon: <Edit3 size={13} /> }] : []),
  ]

  return (
    <DashboardLayout>
      <div className="cr-page cr-page--flush">
        {/* Header with breadcrumb + tabs */}
        <div style={{ padding: '10px 24px 0', background: 'var(--bg-default)', borderBottom: '1px solid var(--border-default)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 }}>
            <div className="cr-doc-breadcrumb">
              <button style={{ background: 'none', border: 'none', color: 'var(--text-link)', cursor: 'pointer', fontSize: 12, padding: 0 }} onClick={() => navigate('/projects')}>
                Projects
              </button>
              <ChevronRight size={10} />
              <strong style={{ color: 'var(--text-primary)', fontSize: 12 }}>{currentProject.name}</strong>
              <span className={`cr-severity ${roleBadgeClass(currentProject.memberRole)}`} style={{ marginLeft: 8 }}>
                {currentProject.memberRole}
              </span>
            </div>
            
            {/* Global Search Bar */}
            <div style={{ width: 300, zIndex: 100 }}>
              <CodeSearchPanel projectId={currentProject.id} commitHash={latestCommitHash || 'HEAD'} compact={true} />
            </div>
          </div>
          {error && (
            <div style={{ padding: '6px 12px', marginBottom: 8, borderRadius: 'var(--radius-md)', background: 'var(--severity-critical-glow)', border: '1px solid var(--severity-critical)', fontSize: 12, color: 'var(--severity-critical)' }}>
              {error}
            </div>
          )}
          <div className="cr-tabs" style={{ border: 'none', padding: 0, background: 'transparent' }}>
            {tabs.map(t => (
              <button key={t.key} className={`cr-tab ${activeTab === t.key ? 'cr-tab--active' : ''}`} onClick={() => handleTabChange(t.key as any)}
                style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                {t.icon} {t.label}
              </button>
            ))}
          </div>
        </div>

        <div style={{ padding: 24, maxWidth: 1000 }}>
          {/* ── Overview ── */}
          {activeTab === 'overview' && (
            <ProjectOverviewPanel
              currentProject={currentProject}
              canEditDocs={canEditDocs}
              analysisLoading={analysisLoading}
              handleTabChange={handleTabChange}
            />
          )}

          {/* ── Architecture ── */}
          {activeTab === 'architecture' && (
            <div className="cr-stack" style={{ gap: 24 }}>
              {analysisLoading ? (
                <div className="flex justify-center p-12">
                  <Loader2 className="animate-spin text-blue-500" size={32} />
                </div>
              ) : !latestCommitHash ? (
                <div className="cr-doc-empty">{resolverError || 'No analyzed commit found for this project yet.'}</div>
              ) : (
                <div className="space-y-6">
                  <div className="cr-analysis-card intel-panel border-l-4 border-l-blue-500">
                    <div className="cr-analysis-card-header intel-panel-header">
                      <div className="intel-panel-title-wrap">
                        <h4>System Intelligence Active</h4>
                        <span className="intel-panel-subtitle">
                          {resolverState.replace('_', ' ')} for {publishedIntelligenceView?.refName || 'this project'}
                        </span>
                      </div>
                      <span className="intel-chip">{latestCommitHash.substring(0, 7)}</span>
                      <IntelligenceStatusBadge state={resolverState as any} />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 gap-6">
                    <div className="cr-analysis-card intel-panel">
                      <div className="cr-analysis-card-header intel-panel-header">
                        <div className="intel-panel-title-wrap">
                          <h4>Architecture Graph</h4>
                          <span className="intel-panel-subtitle">Repository-level knowledge graph</span>
                        </div>
                      </div>
                      <div className="intel-panel-body">
                        <ArchitectureGraphViewer projectId={currentProject.id} commitHash={latestCommitHash} />
                      </div>
                    </div>

                    <div className="cr-analysis-card intel-panel">
                      <div className="cr-analysis-card-header intel-panel-header">
                        <div className="intel-panel-title-wrap">
                          <h4>Dependency Graph</h4>
                          <span className="intel-panel-subtitle">Module-level dependencies and cycle detection</span>
                        </div>
                      </div>
                      <div className="intel-panel-body">
                        <DependencyGraphViewer projectId={currentProject.id} commitHash={latestCommitHash} />
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── APIs & Flows ── */}
          {activeTab === 'apis_flows' && (
            <div className="cr-stack" style={{ gap: 24 }}>
              {analysisLoading ? (
                <div className="flex justify-center p-12">
                  <Loader2 className="animate-spin text-blue-500" size={32} />
                </div>
              ) : !latestCommitHash ? (
                <div className="cr-doc-empty">{resolverError || 'No analyzed commit found for this project yet.'}</div>
              ) : (
                <div className="space-y-6">
                  <div className="cr-analysis-card intel-panel">
                    <div className="cr-analysis-card-header intel-panel-header">
                      <div className="intel-panel-title-wrap">
                        <h4>Execution Traces</h4>
                        <span className="intel-panel-subtitle">Controller to service request flow sequences</span>
                      </div>
                    </div>
                    <div className="intel-panel-body">
                      <CallGraphViewer projectId={currentProject.id} commitHash={latestCommitHash} />
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── Documents ── */}
          {activeTab === 'documents' && <DocumentList projectId={currentProject.id} canManage={canEditDocs} />}

          {/* ── Team (navigates to dedicated page) ── */}
          {activeTab === 'team' && (() => { navigate(`/projects/${id}/team`); return null })()}

          {/* ── Members ── */}
          {activeTab === 'members' && (
            <ProjectMembersPanel
              currentProject={currentProject}
              canManageProject={canManageProject}
              isOwner={isOwner}
              user={user}
              isLoading={isLoading}
              inviteEmail={inviteEmail}
              setInviteEmail={setInviteEmail}
              inviteRole={inviteRole}
              setInviteRole={setInviteRole}
              inviteError={inviteError}
              handleInvite={handleInvite}
              handleChangeRole={handleChangeRole}
              handleRemoveMember={handleRemoveMember}
              handleCancelInvitation={handleCancelInvitation}
            />
          )}

          {/* ── Versioning ── */}
          {activeTab === 'versioning' && canEditDocs && (
            <ProjectVersioningPanel
              docVersions={docVersions}
              versionsLoading={versionsLoading}
              versionFilter={versionFilter}
              setVersionFilter={setVersionFilter}
              filteredVersions={filteredVersions}
              currentProject={currentProject}
              handleTabChange={handleTabChange}
              navigate={navigate}
            />
          )}

          {/* ── Settings ── */}
          {activeTab === 'settings' && canManageProject && (
            <ProjectSettingsPanel
              currentProject={currentProject}
              isEditing={isEditing}
              setIsEditing={setIsEditing}
              editForm={editForm}
              handleEditChange={handleEditChange}
              handleSaveChanges={handleSaveChanges}
              isLoading={isLoading}
              autoGenerateDocs={autoGenerateDocs}
              handleToggleAutoGenerate={handleToggleAutoGenerate}
              settingsLoading={settingsLoading}
              githubToken={githubToken}
              setGithubToken={setGithubToken}
              showGithubToken={showGithubToken}
              setShowGithubToken={setShowGithubToken}
              handleSaveGithubToken={handleSaveGithubToken}
              handleClearGithubToken={handleClearGithubToken}
              docGenMessage={docGenMessage}
              handleTriggerDocGeneration={handleTriggerDocGeneration}
              docGenLoading={docGenLoading}
              isOwner={isOwner}
              setShowDeleteConfirm={setShowDeleteConfirm}
            />
          )}
        </div>

        {/* Delete modal */}
        {showDeleteConfirm && (
          <div style={{ position: 'fixed', inset: 0, zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)' }} onClick={() => setShowDeleteConfirm(false)}>
            <div style={{ background: 'var(--bg-default)', border: '1px solid var(--severity-critical)', borderRadius: 'var(--radius-lg)', width: '100%', maxWidth: 400, overflow: 'hidden' }} onClick={(e) => e.stopPropagation()}>
              <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border-default)' }}>
                <h3 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: 'var(--severity-critical)' }}>Delete Project</h3>
              </div>
              <div style={{ padding: 16 }}>
                <p style={{ fontSize: 13, color: 'var(--text-secondary)', margin: '0 0 16px' }}>Are you sure you want to delete <strong>{currentProject.name}</strong>? This action cannot be undone.</p>
                <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
                  <button className="cr-doc-btn" onClick={() => setShowDeleteConfirm(false)}>Cancel</button>
                  <button className="cr-doc-btn" style={{ background: 'var(--severity-critical)', color: '#fff', border: 'none' }} onClick={handleDelete} disabled={isLoading}>
                    {isLoading ? 'Deleting...' : 'Delete'}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Analysis Progress Modal */}
      {showProgressModal && docGenRunId && id && (
        <AnalysisProgressModal
          projectId={id}
          runId={docGenRunId}
          projectName={currentProject?.name}
          onDismiss={() => setShowProgressModal(false)}
          onComplete={handleRunComplete}
        />
      )}
    </DashboardLayout>
  )
}

export default ProjectDetail
