import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import { fetchProjects, createProject, clearError } from '../store/slices/projectsSlice'
import DashboardLayout from '../components/DashboardLayout'
import { motion } from 'framer-motion'
import { Book, Github, Clock, Plus, Search } from 'lucide-react'

const Projects = () => {
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const { projects, isLoading, error } = useAppSelector((state) => state.projects)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [formData, setFormData] = useState({ name: '', description: '', githubUrl: '', autoGenerateDocs: false, githubAccessToken: '' })
  const [showToken, setShowToken] = useState(false)
  const [formError, setFormError] = useState('')
  const [searchQuery, setSearchQuery] = useState('')

  useEffect(() => { dispatch(fetchProjects()) }, [dispatch])
  useEffect(() => { dispatch(clearError()) }, [dispatch])

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target
    if (type === 'checkbox') setFormData((prev) => ({ ...prev, [name]: (e.target as HTMLInputElement).checked }))
    else setFormData((prev) => ({ ...prev, [name]: value }))
  }

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault(); setFormError('')
    if (!formData.name.trim()) { setFormError('Project name is required'); return }
    if (!formData.githubUrl.trim()) { setFormError('GitHub URL is required'); return }
    try { new URL(formData.githubUrl) } catch { setFormError('Please enter a valid GitHub URL'); return }
    const payload = { name: formData.name, description: formData.description || undefined, githubUrl: formData.githubUrl, autoGenerateDocs: formData.autoGenerateDocs, githubAccessToken: formData.githubAccessToken || undefined }
    const result = await dispatch(createProject(payload))
    if (createProject.fulfilled.match(result)) {
      setShowCreateModal(false); setFormData({ name: '', description: '', githubUrl: '', autoGenerateDocs: false, githubAccessToken: '' })
      setShowToken(false); navigate(`/projects/${result.payload.id}`)
    }
  }

  const closeModal = () => {
    setShowCreateModal(false); setFormData({ name: '', description: '', githubUrl: '', autoGenerateDocs: false, githubAccessToken: '' })
    setShowToken(false); setFormError('')
  }

  const filteredProjects = projects.filter(p =>
    p.name.toLowerCase().includes(searchQuery.toLowerCase()) || (p.description && p.description.toLowerCase().includes(searchQuery.toLowerCase()))
  )

  return (
    <DashboardLayout>
      <motion.div className="cr-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.2 }}>
        <div className="cr-page-header">
          <div>
            <h1 className="cr-page-title">Projects</h1>
            <p className="cr-page-subtitle">Track repositories, automate docs, keep architecture current.</p>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '5px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)' }}>
              <Search size={14} style={{ color: 'var(--text-muted)' }} />
              <input type="text" placeholder="Find project..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)}
                style={{ border: 'none', background: 'transparent', color: 'var(--text-primary)', fontSize: 12, outline: 'none', width: 160 }} />
            </div>
            <button className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600 }} onClick={() => setShowCreateModal(true)}>
              <Plus size={14} /> New Project
            </button>
          </div>
        </div>

        {error && <div style={{ padding: '8px 12px', marginBottom: 12, borderRadius: 'var(--radius-md)', background: 'var(--severity-critical-glow)', border: '1px solid var(--severity-critical)', fontSize: 13, color: 'var(--severity-critical)' }}>{error}</div>}

        {isLoading ? (
          <div className="cr-loading"><div className="cr-spinner" /></div>
        ) : filteredProjects.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '48px 16px', color: 'var(--text-muted)' }}>
            <Book size={32} style={{ opacity: 0.3, marginBottom: 12 }} />
            <h3 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>No projects found</h3>
            <p style={{ fontSize: 13, marginBottom: 12 }}>{projects.length === 0 ? 'Create your first project to get started.' : 'Try adjusting your search.'}</p>
            {projects.length === 0 && <button className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600 }} onClick={() => setShowCreateModal(true)}>Create Project</button>}
          </div>
        ) : (
          <div className="cr-settings-list">
            {filteredProjects.map((project) => (
              <Link to={`/projects/${project.id}`} key={project.id} style={{ textDecoration: 'none', color: 'inherit', display: 'block' }}>
                <div className="cr-settings-row" style={{ cursor: 'pointer', gap: 12 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, flex: 2 }}>
                    <Book size={16} style={{ color: 'var(--accent-primary)', flexShrink: 0 }} />
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{project.name}</div>
                      <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 1 }}>{project.description || 'No description'}</div>
                    </div>
                  </div>
                  {project.githubUrl && (
                    <span style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: 'var(--text-muted)', flex: 2 }}>
                      <Github size={12} /> {project.githubUrl.replace('https://github.com/', '')}
                    </span>
                  )}
                  <span className="cr-severity cr-severity--info">{project.memberRole}</span>
                  <span style={{ fontSize: 11, color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: 4, whiteSpace: 'nowrap' }}>
                    <Clock size={11} /> {new Date(project.createdAt).toLocaleDateString()}
                  </span>
                </div>
              </Link>
            ))}
          </div>
        )}

        {/* Create Modal */}
        {showCreateModal && (
          <div style={{ position: 'fixed', inset: 0, zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)' }} onClick={closeModal}>
            <div style={{ background: 'var(--bg-default)', border: '1px solid var(--border-default)', borderRadius: 'var(--radius-lg)', width: '100%', maxWidth: 480, overflow: 'hidden' }} onClick={(e) => e.stopPropagation()}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 16px', borderBottom: '1px solid var(--border-default)' }}>
                <h3 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>Create New Project</h3>
                <button onClick={closeModal} style={{ width: 28, height: 28, display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-muted)', cursor: 'pointer' }}>×</button>
              </div>
              <form onSubmit={handleCreateProject} style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>Project Name *</label>
                  <input type="text" name="name" value={formData.name} onChange={handleChange} placeholder="e.g. backend-service" autoFocus
                    style={{ width: '100%', padding: '7px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-primary)', fontSize: 13, outline: 'none' }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>Description</label>
                  <textarea name="description" value={formData.description} onChange={handleChange} placeholder="Short description" rows={2}
                    style={{ width: '100%', padding: '7px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-primary)', fontSize: 13, outline: 'none', resize: 'vertical' }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>GitHub URL *</label>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)' }}>
                    <Github size={14} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
                    <input type="url" name="githubUrl" value={formData.githubUrl} onChange={handleChange} placeholder="https://github.com/user/repo" required
                      style={{ border: 'none', background: 'transparent', color: 'var(--text-primary)', fontSize: 13, outline: 'none', flex: 1 }} />
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <input type="checkbox" name="autoGenerateDocs" id="autoGenerateDocs" checked={formData.autoGenerateDocs} onChange={handleChange} />
                  <label htmlFor="autoGenerateDocs" style={{ fontSize: 12, color: 'var(--text-secondary)' }}>Auto-generate docs on push</label>
                </div>
                {formData.autoGenerateDocs && (
                  <div>
                    <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>GitHub Token</label>
                    <div style={{ display: 'flex', gap: 6 }}>
                      <input type={showToken ? 'text' : 'password'} name="githubAccessToken" value={formData.githubAccessToken} onChange={handleChange} placeholder="ghp_xxx"
                        style={{ flex: 1, padding: '7px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-primary)', fontSize: 12, outline: 'none' }} />
                      <button type="button" className="cr-doc-btn" onClick={() => setShowToken(!showToken)}>{showToken ? 'Hide' : 'Show'}</button>
                    </div>
                  </div>
                )}
                {formError && <div style={{ fontSize: 12, color: 'var(--severity-critical)' }}>{formError}</div>}
                {error && <div style={{ fontSize: 12, color: 'var(--severity-critical)' }}>{error}</div>}
                <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', paddingTop: 4 }}>
                  <button type="button" className="cr-doc-btn" onClick={closeModal}>Cancel</button>
                  <button type="submit" className="cr-doc-btn" style={{ background: 'var(--accent-primary)', color: '#fff', border: 'none' }} disabled={isLoading}>{isLoading ? 'Creating...' : 'Create'}</button>
                </div>
              </form>
            </div>
          </div>
        )}
      </motion.div>
    </DashboardLayout>
  )
}

export default Projects
