import { useEffect, useState, useMemo, useRef } from 'react'
import { useParams, useNavigate, useSearchParams } from 'react-router-dom'
import { useAppDispatch, useAppSelector } from '../store/hooks'
import {
  fetchProjectById, updateProject, deleteProject, updateProjectSettings,
  inviteMember, cancelInvitation, removeMember, updateMemberRole,
  clearCurrentProject, clearError,
} from '../store/slices/projectsSlice'
import { projectsApi, documentsApi, webhookApi, DocumentVersion, WebhookRun, IntelligenceView } from '../services/api'
import DashboardLayout from '../components/DashboardLayout'
import DocumentList from '../components/DocumentList'
import DependencyGraphViewer from '../components/DependencyGraphViewer'
import ArchitectureGraphViewer from '../components/ArchitectureGraphViewer'
import CallGraphViewer from '../components/CallGraphViewer'
import IntelligenceOverviewWidget from '../components/IntelligenceOverviewWidget'
import IntelligenceApisWidget from '../components/IntelligenceApisWidget'
import IntelligenceStatusBadge from '../components/IntelligenceStatusBadge'
import { Github, Users, Users2, Clock, Shield, Trash2, ChevronRight, Eye, EyeOff, Tag, GitBranch, FileText, Edit3, History, Sparkles, CheckCircle2, AlertCircle, X, Loader2 } from 'lucide-react'
import { useIntelligenceViewResolver } from '../hooks/useIntelligenceViewResolver'

const inputStyle: React.CSSProperties = {
  width: '100%', padding: '7px 10px', borderRadius: 'var(--radius-md)',
  border: '1px solid var(--border-default)', background: 'var(--bg-subtle)',
  color: 'var(--text-primary)', fontSize: 13, outline: 'none',
}

/** Role badge color mapping */
const roleBadgeClass = (role: string) => {
  switch (role) {
    case 'owner': return 'cr-severity--critical'
    case 'admin': return 'cr-severity--high'
    case 'editor': return 'cr-severity--medium'
    default: return 'cr-severity--info'
  }
}

const ProjectDetail = () => {
  const { id } = useParams<{ id: string }>()
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()
  const { currentProject, isLoading, error } = useAppSelector((s) => s.projects)
  const { user } = useAppSelector((s) => s.auth)

  type TabType = 'overview' | 'intelligence' | 'documents' | 'team' | 'members' | 'versioning' | 'settings'
  const [activeTab, setActiveTab] = useState<TabType>('overview')
  const [isEditing, setIsEditing] = useState(false)
  const [editForm, setEditForm] = useState({ name: '', description: '' })
  const [inviteEmail, setInviteEmail] = useState('')
  const [inviteRole, setInviteRole] = useState<'member' | 'admin'>('member')
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [inviteError, setInviteError] = useState('')
  const [autoGenerateDocs, setAutoGenerateDocs] = useState(false)
  const [githubToken, setGithubToken] = useState('')
  const [showGithubToken, setShowGithubToken] = useState(false)
  const [settingsLoading, setSettingsLoading] = useState(false)
  const [docGenLoading, setDocGenLoading] = useState(false)
  const [docGenMessage, setDocGenMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const [docGenRunId, setDocGenRunId] = useState<string | null>(null)
  const [docGenToast, setDocGenToast] = useState<{ type: 'info' | 'success' | 'error'; title: string; message: string } | null>(null)
  const pollCountRef = useRef(0)

  // Versioning state
  const [docVersions, setDocVersions] = useState<DocumentVersion[]>([])
  const [versionsLoading, setVersionsLoading] = useState(false)
  const [versionFilter, setVersionFilter] = useState('')

  // Intelligence state
  const [analysisLoading, setAnalysisLoading] = useState(false)
  const [latestCommitHash, setLatestCommitHash] = useState('')
  const [publishedIntelligenceView, setPublishedIntelligenceView] = useState<IntelligenceView | null>(null)
  const {
    loading: resolverLoading,
    error: resolverError,
    state: resolverState,
    activeView,
    commitHash: resolvedCommitHash,
  } = useIntelligenceViewResolver(currentProject?.id)


  const handleTabChange = (nextTab: TabType) => {
    setActiveTab(nextTab)
    const nextParams = new URLSearchParams(searchParams)
    if (nextTab === 'intelligence') {
      nextParams.set('tab', 'intelligence')
    } else {
      nextParams.delete('tab')
    }
    setSearchParams(nextParams, { replace: true })
  }


  useEffect(() => { if (id) dispatch(fetchProjectById(id)); return () => { dispatch(clearCurrentProject()) } }, [dispatch, id])
  useEffect(() => {
    const tabParam = searchParams.get('tab')
    if (tabParam === 'intelligence' && activeTab !== 'intelligence') {
      setActiveTab('intelligence')
    }
    if (tabParam !== 'intelligence' && activeTab === 'intelligence') {
      setActiveTab('overview')
    }
  }, [searchParams, activeTab])

  useEffect(() => {
    if (currentProject) {
      setEditForm({ name: currentProject.name, description: currentProject.description || '' })
      setAutoGenerateDocs(currentProject.settings?.autoGenerateDocs || false)
      setGithubToken('')

    }
  }, [currentProject])
  useEffect(() => {
    setAnalysisLoading(resolverLoading)
    setPublishedIntelligenceView(activeView)
    setLatestCommitHash(resolvedCommitHash)
  }, [resolverLoading, activeView, resolvedCommitHash])
  useEffect(() => { dispatch(clearError()) }, [dispatch])

  // Load doc versions when versioning tab is active
  useEffect(() => {
    if (activeTab === 'versioning' && id) {
      setVersionsLoading(true)
      documentsApi.list(id).then(r => { setDocVersions(r.data.documents); setVersionsLoading(false) })
        .catch(() => setVersionsLoading(false))
    }
  }, [activeTab, id])

  // Permission tiers
  const isOwner = currentProject?.memberRole === 'owner'
  const isAdmin = currentProject?.memberRole === 'admin'
  const isEditor = currentProject?.memberRole === 'editor'
  const canManageProject = isOwner || isAdmin               // settings, members, delete
  const canEditDocs = isOwner || isAdmin || isEditor        // edit documents, view versioning

  const filteredVersions = useMemo(() => {
    if (!versionFilter.trim()) return docVersions
    const q = versionFilter.toLowerCase()
    return docVersions.filter(d =>
      d.commit.toLowerCase().includes(q) ||
      d.metadata?.branch?.toLowerCase().includes(q) ||
      d.metadata?.tags?.some(t => t.toLowerCase().includes(q)) ||
      d.metadata?.version?.toLowerCase().includes(q)
    )
  }, [docVersions, versionFilter])

  const handleEditChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setEditForm((p) => ({ ...p, [e.target.name]: e.target.value }))
  }
  const handleSaveChanges = async () => {
    if (!id || !editForm.name.trim()) return
    const r = await dispatch(updateProject({ id, data: editForm }))
    if (updateProject.fulfilled.match(r)) setIsEditing(false)
  }
  const handleDelete = async () => {
    if (!id) return
    const r = await dispatch(deleteProject(id))
    if (deleteProject.fulfilled.match(r)) navigate('/projects')
  }
  const handleInvite = async (e: React.FormEvent) => {
    e.preventDefault(); setInviteError('')
    if (!id || !inviteEmail.trim()) { setInviteError('Email required'); return }
    const r = await dispatch(inviteMember({ projectId: id, email: inviteEmail, role: inviteRole }))
    if (inviteMember.fulfilled.match(r)) setInviteEmail('')
    else if (inviteMember.rejected.match(r)) setInviteError(r.payload as string)
  }
  const handleCancelInvitation = async (invitationId: string) => { if (id) dispatch(cancelInvitation({ projectId: id, invitationId })) }
  const handleRemoveMember = async (memberId: string) => { if (id) dispatch(removeMember({ projectId: id, memberId })) }
  const handleChangeRole = async (memberId: string, newRole: string) => { if (id) dispatch(updateMemberRole({ projectId: id, memberId, role: newRole })) }
  const handleToggleAutoGenerate = async () => {
    if (!id) return; setSettingsLoading(true)
    const v = !autoGenerateDocs
    const r = await dispatch(updateProjectSettings({ id, data: { autoGenerateDocs: v } }))
    if (updateProjectSettings.fulfilled.match(r)) setAutoGenerateDocs(v)
    setSettingsLoading(false)
  }
  const handleSaveGithubToken = async () => {
    if (!id) return; setSettingsLoading(true)
    await dispatch(updateProjectSettings({ id, data: { githubAccessToken: githubToken || null } }))
    setSettingsLoading(false); setGithubToken(''); setShowGithubToken(false)
  }
  const handleClearGithubToken = async () => {
    if (!id) return; setSettingsLoading(true)
    await dispatch(updateProjectSettings({ id, data: { githubAccessToken: null } }))
    setSettingsLoading(false)
  }
  const handleTriggerDocGeneration = async () => {
    if (!id) return; setDocGenLoading(true); setDocGenMessage(null)
    try {
      const response = await projectsApi.triggerDocGeneration(id)
      const runId = response.data.runId
      setDocGenMessage({ type: 'success', text: runId ? 'Doc generation started. Tracking progress…' : 'Doc generation started!' })
      setDocGenToast({
        type: 'info',
        title: 'Generating documentation',
        message: 'Started. We will update progress as stages complete.',
      })
      pollCountRef.current = 0
      setDocGenRunId(runId || null)
    } catch (err: any) {
      const detail = err.response?.data?.detail || 'Failed'
      setDocGenMessage({ type: 'error', text: detail })
      setDocGenToast({ type: 'error', title: 'Generation failed', message: detail })
    } finally { setDocGenLoading(false) }
  }

  useEffect(() => {
    if (!id || !docGenRunId) return

    let active = true
    const poll = async () => {
      try {
        const response = await webhookApi.getRuns(id)
        const run = response.data.runs.find((r) => r.id === docGenRunId) as WebhookRun | undefined
        if (!run || !active) return

        const successfulStages = run.stages.filter((s) => s.status === 'SUCCESS').length
        const failedStage = run.stages.find((s) => s.status === 'FAILED')
        const currentStage = run.stages.find((s) => s.status === 'RUNNING')?.stage
        const totalStages = run.event === 'manual' ? 3 : 4

        if (run.status === 'RUNNING') {
          setDocGenToast({
            type: 'info',
            title: 'Generating documentation',
            message: currentStage
              ? `Running ${currentStage.toUpperCase()} (${successfulStages}/${totalStages} complete)`
              : `${successfulStages}/${totalStages} stages complete`,
          })
        } else if (run.status === 'SUCCESS') {
          setDocGenToast({
            type: 'success',
            title: 'Documentation ready',
            message: `Generation completed (${successfulStages}/${totalStages} stages).`,
          })
          setDocGenRunId(null)
        } else if (run.status === 'FAILED') {
          setDocGenToast({
            type: 'error',
            title: 'Generation failed',
            message: failedStage?.error || 'One or more pipeline stages failed.',
          })
          setDocGenRunId(null)
        }

        pollCountRef.current += 1
        if (pollCountRef.current > 120 && run.status === 'RUNNING') {
          setDocGenToast({
            type: 'info',
            title: 'Still processing',
            message: 'Generation is still running in background. You can continue working.',
          })
          setDocGenRunId(null)
        }
      } catch {
        // keep silent; next poll may recover
      }
    }

    void poll()
    const interval = setInterval(poll, 5000)
    return () => {
      active = false
      clearInterval(interval)
    }
  }, [id, docGenRunId])

  if (isLoading && !currentProject) return <DashboardLayout><div className="cr-page"><div className="cr-loading"><div className="cr-spinner" /></div></div></DashboardLayout>
  if (!currentProject) return (
    <DashboardLayout><div className="cr-page" style={{ textAlign: 'center', paddingTop: 64 }}>
      <h3 style={{ fontSize: 16, color: 'var(--text-secondary)' }}>Project not found</h3>
      <button className="cr-doc-btn" style={{ marginTop: 8 }} onClick={() => navigate('/projects')}>Back to Projects</button>
    </div></DashboardLayout>
  )

  // Build tabs list based on permissions
  const tabs: { key: TabType; label: string; icon: React.ReactNode }[] = [
    { key: 'overview', label: 'Overview', icon: <Shield size={13} /> },
    { key: 'intelligence', label: 'Intelligence', icon: <Sparkles size={13} /> },
    { key: 'documents', label: 'Documents', icon: <FileText size={13} /> },
    { key: 'team', label: 'Team', icon: <Users2 size={13} /> },
    { key: 'members', label: 'Members', icon: <Users size={13} /> },
    ...(canEditDocs ? [{ key: 'versioning' as TabType, label: 'Versioning', icon: <History size={13} /> }] : []),
    ...(canManageProject ? [{ key: 'settings' as TabType, label: 'Settings', icon: <Edit3 size={13} /> }] : []),
  ]

  return (
    <DashboardLayout>
      <div className="cr-page cr-page--flush">
        {/* Header with breadcrumb + tabs */}
        <div style={{ padding: '10px 24px 0', background: 'var(--bg-default)', borderBottom: '1px solid var(--border-default)' }}>
          <div className="cr-doc-breadcrumb" style={{ marginBottom: 8 }}>
            <button style={{ background: 'none', border: 'none', color: 'var(--text-link)', cursor: 'pointer', fontSize: 12, padding: 0 }} onClick={() => navigate('/projects')}>Projects</button>
            <ChevronRight size={10} />
            <strong style={{ color: 'var(--text-primary)', fontSize: 12 }}>{currentProject.name}</strong>
            <span className={`cr-severity ${roleBadgeClass(currentProject.memberRole)}`} style={{ marginLeft: 8 }}>{currentProject.memberRole}</span>
          </div>
          {error && <div style={{ padding: '6px 12px', marginBottom: 8, borderRadius: 'var(--radius-md)', background: 'var(--severity-critical-glow)', border: '1px solid var(--severity-critical)', fontSize: 12, color: 'var(--severity-critical)' }}>{error}</div>}
          <div className="cr-tabs" style={{ border: 'none', padding: 0, background: 'transparent' }}>
            {tabs.map(t => (
              <button key={t.key} className={`cr-tab ${activeTab === t.key ? 'cr-tab--active' : ''}`} onClick={() => handleTabChange(t.key)}
                style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                {t.icon} {t.label}
              </button>
            ))}
          </div>
        </div>

        <div style={{ padding: 24, maxWidth: 1000 }}>
          {/* ── Overview ── */}
          {activeTab === 'overview' && (
            <div className="cr-profile-grid" style={{ gridTemplateColumns: '1.4fr 1fr' }}>
              <div className="cr-stack">
                <div className="cr-card">
                  <div className="cr-card-header">
                    <h3 className="cr-card-title"><Shield size={14} /> Project Info</h3>
                  </div>
                  <div className="cr-card-body">
                    <p style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 4 }}>{currentProject.name}</p>
                    <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 16 }}>{currentProject.description || 'No description'}</p>
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      <button className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600 }} onClick={() => handleTabChange('documents')}>Open Documents</button>
                      {canEditDocs && <button className="cr-doc-btn" style={{ padding: '6px 14px' }} onClick={() => handleTabChange('versioning')}><History size={12} /> Versioning</button>}
                      {currentProject.githubUrl && (
                        <a className="cr-doc-btn" href={currentProject.githubUrl} target="_blank" rel="noopener noreferrer" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, textDecoration: 'none' }}>
                          <Github size={12} /> GitHub
                        </a>
                      )}
                    </div>
                  </div>
                </div>

                {/* Intelligence Widgets Removed as per request */}

                {analysisLoading && (
                  <div className="bg-[var(--bg-default)] border border-[var(--border-default)] rounded-xl h-[400px] flex flex-col items-center justify-center space-y-4 shadow-sm">
                    <Loader2 className="w-10 h-10 text-blue-500 animate-spin" />
                    <p className="text-slate-500 font-medium">Reconstructing project intelligence...</p>
                  </div>
                )}
              </div>

              <div className="cr-stack">
                <div className="cr-card">
                  <div className="cr-card-header"><h3 className="cr-card-title">Quick Stats</h3></div>
                  <div className="cr-card-body">
                    <div className="cr-activity-grid">
                      <div className="cr-activity-item"><span className="cr-activity-value">{currentProject.members?.length || 0}</span><span className="cr-activity-label">Members</span></div>
                      <div className="cr-activity-item"><span className="cr-activity-value">{currentProject.pendingInvitations?.length || 0}</span><span className="cr-activity-label">Invites</span></div>
                      <div className="cr-activity-item"><span className="cr-activity-value">{currentProject?.settings?.autoGenerateDocs ? 'On' : 'Off'}</span><span className="cr-activity-label">Auto Docs</span></div>
                      <div className="cr-activity-item"><span className="cr-activity-value">{currentProject?.settings?.hasGithubToken ? '✓' : '✗'}</span><span className="cr-activity-label">Token</span></div>
                    </div>
                  </div>
                </div>
                <div className="cr-card">
                  <div className="cr-card-header"><h3 className="cr-card-title"><Clock size={14} /> Timeline</h3></div>
                  <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
                    <div className="cr-settings-row"><span className="cr-settings-label">Created</span><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{new Date(currentProject.createdAt).toLocaleString()}</span></div>
                    <div className="cr-settings-row"><span className="cr-settings-label">Updated</span><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{new Date(currentProject.updatedAt).toLocaleString()}</span></div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ── Intelligence ── */}
          {activeTab === 'intelligence' && (
            <div className="cr-stack" style={{ gap: 24 }}>
              {analysisLoading ? (
                <div style={{ display: 'flex', justifyContent: 'center', padding: 48 }}>
                  <Loader2 className="cr-spinner text-blue-500" size={32} />
                </div>
              ) : !latestCommitHash ? (
                <div className="cr-doc-empty">{resolverError || 'No analyzed commit found for this project yet.'}</div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
                  <div className="cr-card" style={{ borderLeft: '4px solid var(--accent-primary)' }}>
                    <div className="cr-card-header" style={{ padding: '16px 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <div>
                        <h4 style={{ margin: 0, fontSize: 16, fontWeight: 600, color: 'var(--text-primary)' }}>System Intelligence Active</h4>
                        <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>
                          {resolverState.replace('_', ' ')} for {publishedIntelligenceView?.refName || 'this project'}
                        </span>
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                        <span style={{ background: 'var(--bg-subtle)', padding: '4px 8px', borderRadius: 6, fontSize: 13, fontFamily: 'var(--font-mono)' }}>{latestCommitHash.substring(0, 7)}</span>
                        <IntelligenceStatusBadge state={resolverState as any} />
                      </div>
                    </div>
                  </div>

                  <IntelligenceOverviewWidget projectId={currentProject.id} commitHash={latestCommitHash} />
                  
                  <DependencyGraphViewer projectId={currentProject.id} commitHash={latestCommitHash} />
                  
                  <ArchitectureGraphViewer projectId={currentProject.id} commitHash={latestCommitHash} />
                  
                  <CallGraphViewer projectId={currentProject.id} commitHash={latestCommitHash} />
                  
                  <div className="cr-card">
                      <div className="cr-card-header">
                          <h3 className="cr-card-title">API Endpoints</h3>
                      </div>
                      <div className="cr-card-body">
                          <IntelligenceApisWidget projectId={currentProject.id} commitHash={latestCommitHash} />
                      </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Search tab removed - search is inside Intelligence */}

          {/* ── Documents ── */}
          {activeTab === 'documents' && <DocumentList projectId={currentProject.id} canManage={canEditDocs} />}

          {/* ── Team (navigates to dedicated page) ── */}
          {activeTab === 'team' && (() => { navigate(`/projects/${id}/team`); return null })()}

          {/* ── Members ── */}
          {activeTab === 'members' && (
            <div className="cr-stack">
              {canManageProject && (
                <div className="cr-card">
                  <div className="cr-card-header"><h3 className="cr-card-title"><Users size={14} /> Invite Member</h3></div>
                  <div className="cr-card-body">
                    <form onSubmit={handleInvite} style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      <input type="email" value={inviteEmail} onChange={(e) => setInviteEmail(e.target.value)} placeholder="Email address" style={{ ...inputStyle, flex: 2, minWidth: 180 }} />
                      <select value={inviteRole} onChange={e => setInviteRole(e.target.value as 'member' | 'admin')}
                        style={{ padding: '6px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-secondary)', fontSize: 12 }}>
                        <option value="member">Member</option>
                        <option value="admin">Admin</option>
                      </select>
                      <button type="submit" className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600, background: 'var(--accent-primary)', color: '#fff', border: 'none' }} disabled={isLoading}>Send</button>
                    </form>
                    {inviteError && <div style={{ fontSize: 12, color: 'var(--severity-critical)', marginTop: 6 }}>{inviteError}</div>}
                  </div>
                </div>
              )}

              {/* Role legend */}
              <div className="cr-card">
                <div className="cr-card-header"><h3 className="cr-card-title">Role Permissions</h3></div>
                <div className="cr-card-body" style={{ display: 'flex', gap: 16, flexWrap: 'wrap', fontSize: 11, color: 'var(--text-muted)' }}>
                  <div><span className={`cr-severity ${roleBadgeClass('owner')}`}>owner</span> — full control</div>
                  <div><span className={`cr-severity ${roleBadgeClass('admin')}`}>admin</span> — settings + members</div>
                  <div><span className={`cr-severity ${roleBadgeClass('editor')}`}>editor</span> — edit docs + versioning</div>
                  <div><span className={`cr-severity ${roleBadgeClass('member')}`}>member</span> — read-only</div>
                </div>
              </div>

              <div className="cr-card">
                <div className="cr-card-header"><h3 className="cr-card-title">Members ({currentProject.members?.length || 0})</h3></div>
                <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
                  {currentProject.members?.map((m) => (
                    <div key={m.id} className="cr-settings-row">
                      <div style={{ display: 'flex', flexDirection: 'column' }}>
                        <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{m.username}</span>
                        <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{m.email}</span>
                      </div>
                      {canManageProject && m.userId !== user?.id ? (
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                          <select value={m.role} onChange={(e) => handleChangeRole(m.id, e.target.value)} disabled={isLoading}
                            style={{ padding: '3px 8px', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-secondary)', fontSize: 12 }}>
                            <option value="member">Member</option>
                            <option value="editor">Editor</option>
                            <option value="admin">Admin</option>
                            {isOwner && <option value="owner">Owner</option>}
                          </select>
                          {m.role !== 'owner' && <button className="cr-token-btn" style={{ color: 'var(--severity-critical)' }} onClick={() => handleRemoveMember(m.id)}><Trash2 size={14} /></button>}
                        </div>
                      ) : <span className={`cr-severity ${roleBadgeClass(m.role)}`}>{m.role}</span>}
                    </div>
                  ))}
                </div>
              </div>

              {canManageProject && currentProject.pendingInvitations && currentProject.pendingInvitations.length > 0 && (
                <div className="cr-card">
                  <div className="cr-card-header"><h3 className="cr-card-title">Pending Invitations</h3></div>
                  <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
                    {currentProject.pendingInvitations.map((inv) => (
                      <div key={inv.id} className="cr-settings-row">
                        <span style={{ fontSize: 13, color: 'var(--text-primary)' }}>{inv.email}</span>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                          <span className="cr-severity cr-severity--medium">Pending</span>
                          <button className="cr-doc-btn" onClick={() => handleCancelInvitation(inv.id)}>Cancel</button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── Versioning ── */}
          {activeTab === 'versioning' && canEditDocs && (
            <div className="cr-stack">
              <div className="cr-card">
                <div className="cr-card-header">
                  <h3 className="cr-card-title"><History size={14} /> Documentation Versions</h3>
                  <span className="cr-card-meta">{docVersions.length} versions</span>
                </div>
                <div className="cr-card-body" style={{ padding: '8px 16px' }}>
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <input type="text" value={versionFilter} onChange={e => setVersionFilter(e.target.value)} placeholder="Filter by commit, branch, tag..."
                      style={{ ...inputStyle, flex: 1, fontSize: 12 }} />
                    <span style={{ fontSize: 11, color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>{filteredVersions.length} shown</span>
                  </div>
                </div>
              </div>

              {versionsLoading ? (
                <div className="cr-loading"><div className="cr-spinner" /></div>
              ) : filteredVersions.length === 0 ? (
                <div className="cr-doc-empty">No document versions found.</div>
              ) : (
                <div className="cr-settings-list">
                  {filteredVersions.map((doc, idx) => {
                    const isLatest = idx === 0
                    return (
                      <div key={doc.commit} className="cr-settings-row" style={{ gap: 12, flexWrap: 'wrap' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 140 }}>
                          <span className="cr-commit-sha">{doc.commit.substring(0, 7)}</span>
                          {isLatest && <span className="cr-severity cr-severity--low" style={{ fontSize: 9 }}>LATEST</span>}
                        </div>

                        <div style={{ display: 'flex', alignItems: 'center', gap: 6, flex: 1, minWidth: 120 }}>
                          {doc.metadata?.branch && (
                            <span style={{ display: 'flex', alignItems: 'center', gap: 3, fontSize: 11, color: 'var(--text-muted)' }}>
                              <GitBranch size={11} />
                              {doc.metadata.branchUrl ? (
                                <a href={doc.metadata.branchUrl} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--text-link)', textDecoration: 'none' }}>{doc.metadata.branch}</a>
                              ) : doc.metadata.branch}
                            </span>
                          )}
                        </div>

                        <div style={{ display: 'flex', gap: 3, flexWrap: 'wrap' }}>
                          {doc.metadata?.version && (
                            <span className="cr-severity cr-severity--info" style={{ fontSize: 9 }}>v{doc.metadata.version}</span>
                          )}
                          {(doc.metadata?.tags || []).map(tag => (
                            <span key={tag} style={{ display: 'inline-flex', alignItems: 'center', gap: 2, padding: '1px 6px', borderRadius: 3, fontSize: 9, fontWeight: 600, background: 'var(--accent-primary-soft)', color: 'var(--accent-primary)' }}>
                              <Tag size={8} />{tag}
                            </span>
                          ))}
                        </div>

                        <span style={{ fontSize: 11, color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>
                          {doc.metadata?.createdAt ? new Date(doc.metadata.createdAt).toLocaleDateString() : '—'}
                        </span>

                        <div style={{ display: 'flex', gap: 4 }}>
                          <button className="cr-doc-btn" onClick={() => navigate(`/projects/${currentProject.id}/docs/${encodeURIComponent(doc.commit)}`)}>
                            <Eye size={11} /> View
                          </button>
                          {filteredVersions.length >= 2 && idx > 0 && (
                            <button className="cr-doc-btn" onClick={() =>
                              navigate(`/projects/${currentProject.id}/compare?v1=${encodeURIComponent(filteredVersions[0].commit)}&v2=${encodeURIComponent(doc.commit)}`)
                            }>
                              Diff vs Latest
                            </button>
                          )}
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}

              {/* Version comparison helper */}
              {filteredVersions.length >= 2 && (
                <div className="cr-card">
                  <div className="cr-card-header"><h3 className="cr-card-title">Quick Compare</h3></div>
                  <div className="cr-card-body" style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>Compare two versions:</span>
                    <button className="cr-doc-btn" onClick={() => handleTabChange('documents')}>
                      Open Documents → Compare Mode
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* ── Settings ── */}
          {activeTab === 'settings' && canManageProject && (
            <div className="cr-stack">
              <div className="cr-card">
                <div className="cr-card-header"><h3 className="cr-card-title">Project Settings</h3></div>
                {isEditing ? (
                  <div className="cr-card-body" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                    <div><label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>Name</label>
                      <input type="text" name="name" value={editForm.name} onChange={handleEditChange} style={inputStyle} /></div>
                    <div><label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>Description</label>
                      <textarea name="description" value={editForm.description} onChange={handleEditChange} rows={3} style={{ ...inputStyle, resize: 'vertical' }} /></div>
                    <div style={{ display: 'flex', gap: 8 }}>
                      <button className="cr-doc-btn" onClick={() => setIsEditing(false)}>Cancel</button>
                      <button className="cr-doc-btn" style={{ background: 'var(--accent-primary)', color: '#fff', border: 'none' }} onClick={handleSaveChanges} disabled={isLoading}>
                        {isLoading ? 'Saving...' : 'Save'}
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
                    <div className="cr-settings-row"><span className="cr-settings-label">Name</span><span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{currentProject.name}</span></div>
                    <div className="cr-settings-row"><span className="cr-settings-label">Description</span><span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{currentProject.description || 'None'}</span></div>
                    <div className="cr-settings-row"><span className="cr-settings-label">GitHub URL</span><span style={{ fontSize: 12, color: 'var(--text-link)', fontFamily: 'var(--font-mono)' }}>{currentProject.githubUrl || 'Not set'}</span></div>
                    <div className="cr-settings-row" style={{ justifyContent: 'flex-end' }}>
                      <button className="cr-doc-btn" onClick={() => setIsEditing(true)}>Edit</button>
                    </div>
                  </div>
                )}
              </div>

              <div className="cr-card">
                <div className="cr-card-header"><h3 className="cr-card-title">Documentation</h3></div>
                <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
                  <div className="cr-settings-row">
                    <div className="cr-settings-left">
                      <span className="cr-settings-label">Auto-generate</span>
                      <span className="cr-settings-desc">Generate docs on push</span>
                    </div>
                    <button className={`cr-switch ${autoGenerateDocs ? 'cr-switch--on' : ''}`} onClick={handleToggleAutoGenerate} disabled={settingsLoading}>
                      <span className="cr-switch-thumb" />
                    </button>
                  </div>
                  <div className="cr-settings-row cr-settings-row--col">
                    <div className="cr-settings-left">
                      <span className="cr-settings-label">GitHub Token</span>
                      <span className="cr-settings-desc">Required for private repos</span>
                    </div>
                    {currentProject?.settings?.hasGithubToken ? (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%' }}>
                        <span style={{ fontSize: 12, color: 'var(--accent-green)', fontWeight: 600 }}>Token set</span>
                        {currentProject?.settings?.hasWebhook && <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Webhook active</span>}
                        <button className="cr-doc-btn" style={{ marginLeft: 'auto' }} onClick={handleClearGithubToken} disabled={settingsLoading}>Clear</button>
                      </div>
                    ) : (
                      <div className="cr-token-display">
                        <input type={showGithubToken ? 'text' : 'password'} value={githubToken} onChange={(e) => setGithubToken(e.target.value)} placeholder="ghp_xxx"
                          style={{ flex: 1, padding: '5px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-primary)', fontSize: 12, outline: 'none' }} />
                        <button className="cr-token-btn" onClick={() => setShowGithubToken(!showGithubToken)}>{showGithubToken ? <EyeOff size={14} /> : <Eye size={14} />}</button>
                        <button className="cr-doc-btn" style={{ background: 'var(--accent-primary)', color: '#fff', border: 'none' }} onClick={handleSaveGithubToken} disabled={settingsLoading || !githubToken.trim()}>
                          {settingsLoading ? '...' : 'Save'}
                        </button>
                      </div>
                    )}
                  </div>
                  <div className="cr-settings-row cr-settings-row--col">
                    <div className="cr-settings-left">
                      <span className="cr-settings-label">Manual Generation</span>
                      <span className="cr-settings-desc">Trigger docs now</span>
                    </div>
                    {docGenMessage && <div style={{ fontSize: 12, color: docGenMessage.type === 'success' ? 'var(--accent-green)' : 'var(--severity-critical)', marginBottom: 4 }}>{docGenMessage.text}</div>}
                    <button className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600 }} onClick={handleTriggerDocGeneration}
                      disabled={docGenLoading || !currentProject?.settings?.hasGithubToken}>
                      {docGenLoading ? 'Generating...' : 'Generate Now'}
                    </button>
                    {!currentProject?.settings?.hasGithubToken && <span style={{ fontSize: 11, color: 'var(--severity-medium)' }}>Add a token first</span>}
                  </div>
                </div>
              </div>

              {isOwner && (
                <div className="cr-card" style={{ borderColor: 'var(--severity-critical)' }}>
                  <div className="cr-card-header" style={{ background: 'var(--severity-critical-glow)' }}>
                    <h3 className="cr-card-title" style={{ color: 'var(--severity-critical)' }}><Trash2 size={14} /> Danger Zone</h3>
                  </div>
                  <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
                    <div className="cr-settings-row">
                      <div className="cr-settings-left">
                        <span className="cr-settings-label">Delete Project</span>
                        <span className="cr-settings-desc">This cannot be undone</span>
                      </div>
                      <button className="cr-doc-btn" style={{ color: 'var(--severity-critical)', borderColor: 'var(--severity-critical)' }} onClick={() => setShowDeleteConfirm(true)}>Delete</button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Delete modal */}
        {showDeleteConfirm && (
          <div style={{ position: 'fixed', inset: 0, zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)' }} onClick={() => setShowDeleteConfirm(false)}>
            <div style={{ background: 'var(--bg-default)', border: '1px solid var(--severity-critical)', borderRadius: 'var(--radius-lg)', width: '100%', maxWidth: 400, overflow: 'hidden' }} onClick={(e) => e.stopPropagation()}>
              <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border-default)' }}>
                <h3 style={{ margin: 0, fontSize: 14, fontWeight: 700, color: 'var(--severity-critical)' }}>Delete Project</h3>
              </div>
              <div style={{ padding: 16 }}>
                <p style={{ fontSize: 13, color: 'var(--text-secondary)', margin: '0 0 16px' }}>Are you sure you want to delete <strong>{currentProject.name}</strong>? This action cannot be undone.</p>
                <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
                  <button className="cr-doc-btn" onClick={() => setShowDeleteConfirm(false)}>Cancel</button>
                  <button className="cr-doc-btn" style={{ background: 'var(--severity-critical)', color: '#fff', border: 'none' }} onClick={handleDelete} disabled={isLoading}>
                    {isLoading ? 'Deleting...' : 'Delete'}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {docGenToast && (
        <div className="repo-toast-container">
          <div className={`repo-toast repo-toast--${docGenToast.type}`}>
            <div className="repo-toast-icon">
              {docGenToast.type === 'success' && <CheckCircle2 size={18} />}
              {docGenToast.type === 'error' && <AlertCircle size={18} />}
              {docGenToast.type === 'info' && (docGenRunId ? <Loader2 size={18} className="repo-pulse" /> : <Sparkles size={18} className="repo-pulse" />)}
            </div>
            <div className="repo-toast-content">
              <strong className="repo-toast-title">{docGenToast.title}</strong>
              <span className="repo-toast-msg">{docGenToast.message}</span>
            </div>
            <div className="repo-toast-actions">
              <button className="repo-toast-close" onClick={() => setDocGenToast(null)}><X size={14} /></button>
            </div>
          </div>
        </div>
      )}
    </DashboardLayout >
  )
}

export default ProjectDetail
