import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import ProjectDetail from './ProjectDetail'

const mocks = vi.hoisted(() => ({
  resolver: vi.fn(),
  appSelector: vi.fn(),
  appDispatch: vi.fn(() => vi.fn()),
  listDocs: vi.fn().mockResolvedValue({ data: { documents: [] } }),
  getRuns: vi.fn().mockResolvedValue({ data: { runs: [] } }),
}))

vi.mock('../hooks/useIntelligenceViewResolver', () => ({
  useIntelligenceViewResolver: (...args: any[]) => mocks.resolver(...args),
}))

vi.mock('../store/hooks', () => ({
  useAppSelector: (...args: any[]) => mocks.appSelector(...args),
  useAppDispatch: () => mocks.appDispatch(),
}))

vi.mock('../store/slices/projectsSlice', () => ({
  fetchProjectById: () => ({ type: 'projects/fetchById' }),
  updateProject: Object.assign(() => ({ type: 'projects/update' }), { fulfilled: { match: () => false } }),
  deleteProject: Object.assign(() => ({ type: 'projects/delete' }), { fulfilled: { match: () => false } }),
  updateProjectSettings: Object.assign(() => ({ type: 'projects/updateSettings' }), { fulfilled: { match: () => false } }),
  inviteMember: Object.assign(() => ({ type: 'projects/invite' }), { fulfilled: { match: () => false }, rejected: { match: () => false } }),
  cancelInvitation: () => ({ type: 'projects/cancelInvitation' }),
  removeMember: () => ({ type: 'projects/removeMember' }),
  updateMemberRole: () => ({ type: 'projects/updateMemberRole' }),
  clearCurrentProject: () => ({ type: 'projects/clearCurrentProject' }),
  clearError: () => ({ type: 'projects/clearError' }),
}))

vi.mock('../services/api', () => ({
  projectsApi: { triggerDocGeneration: vi.fn() },
  documentsApi: { list: (...args: any[]) => mocks.listDocs(...args) },
  webhookApi: { getRuns: (...args: any[]) => mocks.getRuns(...args) },
}))

vi.mock('../components/DashboardLayout', () => ({ default: ({ children }: any) => <div>{children}</div> }))
vi.mock('../components/DocumentList', () => ({ default: () => <div>document-list</div> }))
vi.mock('../components/CodeSearchPanel', () => ({ default: () => <div>code-search</div> }))
vi.mock('../components/DependencyGraphViewer', () => ({ default: () => <div>dep-graph</div> }))
vi.mock('../components/CallGraphViewer', () => ({ default: () => <div>call-graph</div> }))
vi.mock('../components/ArchitectureGraphViewer', () => ({ default: () => <div>arch-graph</div> }))

describe('ProjectDetail intelligence resolver coverage', () => {
  const mockState = {
    projects: {
      currentProject: {
        id: 'p1',
        name: 'Project One',
        description: 'desc',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        settings: { autoGenerateDocs: false, hasGithubToken: false },
        members: [],
        pendingInvitations: [],
        memberRole: 'owner',
      },
      isLoading: false,
      error: null,
    },
    auth: { user: { id: 'u1', email: 'owner@test.dev' } },
  }

  beforeEach(() => {
    mocks.appSelector.mockImplementation((selector: any) => selector(mockState))
  })

  afterEach(() => {
    cleanup()
    vi.clearAllMocks()
  })

  it('renders intelligence tab using resolved view metadata and normalized state', () => {
    mocks.resolver.mockReturnValue({
      loading: false,
      error: null,
      state: 'published_failed',
      activeView: { refName: 'main' },
      commitHash: 'cafebabe',
    })

    render(
      <MemoryRouter initialEntries={['/projects/p1?tab=architecture']}>
        <Routes>
          <Route path="/projects/:id" element={<ProjectDetail />} />
        </Routes>
      </MemoryRouter>,
    )

    expect(screen.getByText('Published (Failed)')).toBeTruthy()
    expect(screen.getByText('cafebab')).toBeTruthy()
    expect(screen.getByText(/published failed for main/i)).toBeTruthy()
  })
})
