import React, { useEffect, useState } from 'react'

import { motion } from 'framer-motion'
import { Layers, FileCode, ChevronRight } from 'lucide-react'
import { portalApi, PortalArchFile } from '../services/portalApi'
import { MermaidBlock } from '../components/MarkdownRenderer'

interface Props {
    projectId: string;
    commitHash: string;
}

const ArchitectureGraphViewer: React.FC<Props> = ({ projectId, commitHash }) => {
    const [files, setFiles] = useState<PortalArchFile[]>([])
    const [selected, setSelected] = useState<PortalArchFile | null>(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState<string | null>(null)

    useEffect(() => {
        if (!projectId || !commitHash) return
        setLoading(true)
        portalApi.getArchitecture(projectId, commitHash)
            .then(r => {
                const f = r.data.files
                setFiles(f)
                if (f.length > 0) setSelected(f[0])
            })
            .catch(e => setError(e.message))
            .finally(() => setLoading(false))
    }, [projectId, commitHash])

    const isMermaidContent = (content: string) => {
        const t = content.trimStart()
        return (
            t.startsWith('graph') || t.startsWith('flowchart') ||
            t.startsWith('sequenceDiagram') || t.startsWith('classDiagram') ||
            t.startsWith('erDiagram') || t.startsWith('stateDiagram') ||
            t.startsWith('gantt') || t.startsWith('pie') || t.startsWith('```mermaid')
        )
    }

    return (
        <div className="cr-card">
            <div className="cr-card-header">
                <h1 className="cr-card-title">
                    <Layers size={18} />
                    Architecture
                </h1>
                <p className="cr-card-subtitle">System structure, layers, and component relationships</p>
            </div>

            {loading ? (
                <div className="cr-card-body">
                    <div className="cr-loading-skeleton" style={{ height: 400 }} />
                </div>
            ) : error || files.length === 0 ? (
                <div className="cr-card-body">
                    <div className="cr-empty">
                        <Layers size={36} className="text-slate-300" />
                        <p>{error ?? 'No architecture diagrams available for this commit.'}</p>
                        <p style={{ color: 'var(--text-muted)', fontSize: 13, marginTop: 12 }}>Architecture diagrams are generated by the EPIC-2 pipeline.</p>
                    </div>
                </div>
            ) : (
                <div style={{ display: 'flex', borderTop: '1px solid var(--border-default)', minHeight: 500 }}>
                    {/* File list sidebar */}
                    <div style={{ width: 220, borderRight: '1px solid var(--border-default)', background: 'var(--bg-subtle)', display: 'flex', flexDirection: 'column' }}>
                        <div style={{ padding: '12px 16px', fontSize: 12, fontWeight: 600, color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: 6, borderBottom: '1px solid var(--border-default)' }}>
                            <FileCode size={14} />
                            <span>{files.length} Diagram{files.length !== 1 ? 's' : ''}</span>
                        </div>
                        <div style={{ overflowY: 'auto', flex: 1 }}>
                            {files.map((f, i) => (
                                <button
                                    key={i}
                                    onClick={() => setSelected(f)}
                                    style={{
                                        width: '100%', padding: '10px 16px', textAlign: 'left', border: 'none', background: selected?.path === f.path ? 'var(--bg-default)' : 'transparent',
                                        borderLeft: selected?.path === f.path ? '3px solid var(--accent-primary)' : '3px solid transparent',
                                        cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                                        borderBottom: '1px solid var(--border-default)'
                                    }}
                                >
                                    <span style={{ fontSize: 13, color: selected?.path === f.path ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: selected?.path === f.path ? 600 : 400, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                        {f.name}
                                    </span>
                                    {selected?.path === f.path && <ChevronRight size={14} color="var(--accent-primary)" />}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Diagram canvas */}
                    <div style={{ flex: 1, padding: 24, background: 'var(--bg-default)', overflow: 'auto' }}>
                        {selected && (
                            <motion.div
                                key={selected.path}
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                            >
                                <div style={{ marginBottom: 20 }}>
                                    <h3 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-primary)', margin: '0 0 4px' }}>{selected.name}</h3>
                                    <p style={{ fontSize: 12, color: 'var(--text-muted)', margin: 0, fontFamily: 'var(--font-mono)' }}>{selected.path}</p>
                                </div>
                                <div style={{ background: '#fff', padding: 20, borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-default)' }}>
                                    {isMermaidContent(selected.content) ? (
                                        <MermaidBlock code={selected.content.replace(/^```mermaid\n?/, '').replace(/\n?```$/, '')} />
                                    ) : (
                                        <pre style={{ fontSize: 12, fontFamily: 'var(--font-mono)', overflowX: 'auto' }}>{selected.content}</pre>
                                    )}
                                </div>
                            </motion.div>
                        )}
                    </div>
                </div>
            )}
        </div>
    )
}

export default ArchitectureGraphViewer
