import React from 'react'
import { Shield, History, Github, Clock, Loader2 } from 'lucide-react'

interface ProjectOverviewPanelProps {
  currentProject: any
  canEditDocs: boolean
  analysisLoading: boolean
  handleTabChange: (tab: any) => void
}

export const ProjectOverviewPanel: React.FC<ProjectOverviewPanelProps> = ({
  currentProject,
  canEditDocs,
  analysisLoading,
  handleTabChange,
}) => {
  return (
    <div className="cr-profile-grid" style={{ gridTemplateColumns: '1.4fr 1fr' }}>
      <div className="cr-stack">
        <div className="cr-card">
          <div className="cr-card-header">
            <h3 className="cr-card-title"><Shield size={14} /> Project Info</h3>
          </div>
          <div className="cr-card-body">
            <p style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 4 }}>{currentProject.name}</p>
            <p style={{ fontSize: 13, color: 'var(--text-muted)', marginBottom: 16 }}>{currentProject.description || 'No description'}</p>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              <button className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600 }} onClick={() => handleTabChange('documents')}>Open Documents</button>
              {canEditDocs && (
                <button className="cr-doc-btn" style={{ padding: '6px 14px' }} onClick={() => handleTabChange('versioning')}>
                  <History size={12} /> Versioning
                </button>
              )}
              {currentProject.githubUrl && (
                <a className="cr-doc-btn" href={currentProject.githubUrl} target="_blank" rel="noopener noreferrer" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, textDecoration: 'none' }}>
                  <Github size={12} /> GitHub
                </a>
              )}
            </div>
          </div>
        </div>

        {analysisLoading && (
          <div className="bg-[var(--bg-default)] border border-[var(--border-default)] rounded-xl h-[400px] flex flex-col items-center justify-center space-y-4 shadow-sm">
            <Loader2 className="w-10 h-10 text-blue-500 animate-spin" />
            <p className="text-slate-500 font-medium">Reconstructing project intelligence...</p>
          </div>
        )}
      </div>

      <div className="cr-stack">
        <div className="cr-card">
          <div className="cr-card-header"><h3 className="cr-card-title">Quick Stats</h3></div>
          <div className="cr-card-body">
            <div className="cr-activity-grid">
              <div className="cr-activity-item"><span className="cr-activity-value">{currentProject.members?.length || 0}</span><span className="cr-activity-label">Members</span></div>
              <div className="cr-activity-item"><span className="cr-activity-value">{currentProject.pendingInvitations?.length || 0}</span><span className="cr-activity-label">Invites</span></div>
              <div className="cr-activity-item"><span className="cr-activity-value">{currentProject?.settings?.autoGenerateDocs ? 'On' : 'Off'}</span><span className="cr-activity-label">Auto Docs</span></div>
              <div className="cr-activity-item"><span className="cr-activity-value">{currentProject?.settings?.hasGithubToken ? '✓' : '✗'}</span><span className="cr-activity-label">Token</span></div>
            </div>
          </div>
        </div>
        <div className="cr-card">
          <div className="cr-card-header"><h3 className="cr-card-title"><Clock size={14} /> Timeline</h3></div>
          <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
            <div className="cr-settings-row"><span className="cr-settings-label">Created</span><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{new Date(currentProject.createdAt).toLocaleString()}</span></div>
            <div className="cr-settings-row"><span className="cr-settings-label">Updated</span><span style={{ fontSize: 12, color: 'var(--text-muted)' }}>{new Date(currentProject.updatedAt).toLocaleString()}</span></div>
          </div>
        </div>
      </div>
    </div>
  )
}
