import React from 'react'
import { Eye, EyeOff, Trash2 } from 'lucide-react'

const inputStyle: React.CSSProperties = {
  width: '100%', padding: '7px 10px', borderRadius: 'var(--radius-md)',
  border: '1px solid var(--border-default)', background: 'var(--bg-subtle)',
  color: 'var(--text-primary)', fontSize: 13, outline: 'none',
}

interface ProjectSettingsPanelProps {
  currentProject: any
  isEditing: boolean
  setIsEditing: (v: boolean) => void
  editForm: { name: string; description: string }
  handleEditChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void
  handleSaveChanges: () => Promise<void>
  isLoading: boolean
  autoGenerateDocs: boolean
  handleToggleAutoGenerate: () => Promise<void>
  settingsLoading: boolean
  githubToken: string
  setGithubToken: (v: string) => void
  showGithubToken: boolean
  setShowGithubToken: (v: boolean) => void
  handleSaveGithubToken: () => Promise<void>
  handleClearGithubToken: () => Promise<void>
  docGenMessage: { type: 'success' | 'error'; text: string } | null
  handleTriggerDocGeneration: () => Promise<void>
  docGenLoading: boolean
  isOwner: boolean
  setShowDeleteConfirm: (v: boolean) => void
}

export const ProjectSettingsPanel: React.FC<ProjectSettingsPanelProps> = ({
  currentProject,
  isEditing,
  setIsEditing,
  editForm,
  handleEditChange,
  handleSaveChanges,
  isLoading,
  autoGenerateDocs,
  handleToggleAutoGenerate,
  settingsLoading,
  githubToken,
  setGithubToken,
  showGithubToken,
  setShowGithubToken,
  handleSaveGithubToken,
  handleClearGithubToken,
  docGenMessage,
  handleTriggerDocGeneration,
  docGenLoading,
  isOwner,
  setShowDeleteConfirm,
}) => {
  return (
    <div className="cr-stack">
      <div className="cr-card">
        <div className="cr-card-header"><h3 className="cr-card-title">Project Settings</h3></div>
        {isEditing ? (
          <div className="cr-card-body" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>Name</label>
              <input type="text" name="name" value={editForm.name} onChange={handleEditChange} style={inputStyle} />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 4 }}>Description</label>
              <textarea name="description" value={editForm.description} onChange={handleEditChange} rows={3} style={{ ...inputStyle, resize: 'vertical' }} />
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button className="cr-doc-btn" onClick={() => setIsEditing(false)}>Cancel</button>
              <button className="cr-doc-btn" style={{ background: 'var(--accent-primary)', color: '#fff', border: 'none' }} onClick={handleSaveChanges} disabled={isLoading}>
                {isLoading ? 'Saving...' : 'Save'}
              </button>
            </div>
          </div>
        ) : (
          <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
            <div className="cr-settings-row"><span className="cr-settings-label">Name</span><span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{currentProject.name}</span></div>
            <div className="cr-settings-row"><span className="cr-settings-label">Description</span><span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>{currentProject.description || 'None'}</span></div>
            <div className="cr-settings-row"><span className="cr-settings-label">GitHub URL</span><span style={{ fontSize: 12, color: 'var(--text-link)', fontFamily: 'var(--font-mono)' }}>{currentProject.githubUrl || 'Not set'}</span></div>
            <div className="cr-settings-row" style={{ justifyContent: 'flex-end' }}>
              <button className="cr-doc-btn" onClick={() => setIsEditing(true)}>Edit</button>
            </div>
          </div>
        )}
      </div>

      <div className="cr-card">
        <div className="cr-card-header"><h3 className="cr-card-title">Documentation</h3></div>
        <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
          <div className="cr-settings-row">
            <div className="cr-settings-left">
              <span className="cr-settings-label">Auto-generate</span>
              <span className="cr-settings-desc">Generate docs on push</span>
            </div>
            <button className={`cr-switch ${autoGenerateDocs ? 'cr-switch--on' : ''}`} onClick={handleToggleAutoGenerate} disabled={settingsLoading}>
              <span className="cr-switch-thumb" />
            </button>
          </div>
          <div className="cr-settings-row cr-settings-row--col">
            <div className="cr-settings-left">
              <span className="cr-settings-label">GitHub Token</span>
              <span className="cr-settings-desc">Required for private repos</span>
            </div>
            {currentProject?.settings?.hasGithubToken ? (
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%' }}>
                <span style={{ fontSize: 12, color: 'var(--accent-green)', fontWeight: 600 }}>Token set</span>
                {currentProject?.settings?.hasWebhook && <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Webhook active</span>}
                <button className="cr-doc-btn" style={{ marginLeft: 'auto' }} onClick={handleClearGithubToken} disabled={settingsLoading}>Clear</button>
              </div>
            ) : (
              <div className="cr-token-display">
                <input type={showGithubToken ? 'text' : 'password'} value={githubToken} onChange={(e) => setGithubToken(e.target.value)} placeholder="ghp_xxx"
                  style={{ flex: 1, padding: '5px 10px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-default)', background: 'var(--bg-subtle)', color: 'var(--text-primary)', fontSize: 12, outline: 'none' }} />
                <button className="cr-token-btn" onClick={() => setShowGithubToken(!showGithubToken)}>{showGithubToken ? <EyeOff size={14} /> : <Eye size={14} />}</button>
                <button className="cr-doc-btn" style={{ background: 'var(--accent-primary)', color: '#fff', border: 'none' }} onClick={handleSaveGithubToken} disabled={settingsLoading || !githubToken.trim()}>
                  {settingsLoading ? '...' : 'Save'}
                </button>
              </div>
            )}
          </div>
          <div className="cr-settings-row cr-settings-row--col">
            <div className="cr-settings-left">
              <span className="cr-settings-label">Manual Generation</span>
              <span className="cr-settings-desc">Trigger docs now</span>
            </div>
            {docGenMessage && <div style={{ fontSize: 12, color: docGenMessage.type === 'success' ? 'var(--accent-green)' : 'var(--severity-critical)', marginBottom: 4 }}>{docGenMessage.text}</div>}
            <button className="cr-doc-btn" style={{ padding: '6px 14px', fontWeight: 600 }} onClick={handleTriggerDocGeneration}
              disabled={docGenLoading || !currentProject?.settings?.hasGithubToken}>
              {docGenLoading ? 'Generating...' : 'Generate Now'}
            </button>
            {!currentProject?.settings?.hasGithubToken && <span style={{ fontSize: 11, color: 'var(--severity-medium)' }}>Add a token first</span>}
          </div>
        </div>
      </div>

      {isOwner && (
        <div className="cr-card" style={{ borderColor: 'var(--severity-critical)' }}>
          <div className="cr-card-header" style={{ background: 'var(--severity-critical-glow)' }}>
            <h3 className="cr-card-title" style={{ color: 'var(--severity-critical)' }}><Trash2 size={14} /> Danger Zone</h3>
          </div>
          <div className="cr-settings-list" style={{ border: 'none', borderRadius: 0 }}>
            <div className="cr-settings-row">
              <div className="cr-settings-left">
                <span className="cr-settings-label">Delete Project</span>
                <span className="cr-settings-desc">This cannot be undone</span>
              </div>
              <button className="cr-doc-btn" style={{ color: 'var(--severity-critical)', borderColor: 'var(--severity-critical)' }} onClick={() => setShowDeleteConfirm(true)}>Delete</button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
